site_name: MkDocs YouTube Tutorial
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.footer
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: en
  palette:
  - scheme: default
    toggle: 
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: indigo
    accent: deep purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: indigo
    accent: deep purple
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/spacetimeglitch
    - icon: fontawesome/brands/github
      link: https://github.com/robch
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/chambersrob/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      
copyright: |
  &copy; 2024 <a href="https://github.com/robch/" target="_blank" rel="noopener">Rob Chambers</a>
