site_name: BOOK of AI
repo_url: https://github.com/robch/book-of-ai

theme:
  logo: assets/ai.png
  name: material
  icon:
    annotation: material/arrow-right-circle 
  features:
  - navigation.tabs     # once there are multiple books, uncomment this
  - navigation.sections
  - navigation.footer
  - navigation.indexes
  # - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: en
  palette:
  - scheme: default
    toggle: 
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: black
    accent: indigo
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: black
    accent: indigo

extra_css:
  - assets/extra.css
  - assets/cli-toggle.css

extra_javascript:
  - js/cli-toggle.js

extra:
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/spacetimeglitch
    - icon: fontawesome/brands/github
      link: https://github.com/robch
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/chambersrob/

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower      
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs", "docs/snippets", "snippets"]
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

copyright: |
  &copy; 2024 <a href="https://github.com/robch/" target="_blank" rel="noopener">Rob Chambers</a>

nav:
  - HOME: index.md
  - PRE-REQS:
      - INSTALL:
        - "CLI Installation": install-ai-cli.md
      - SETUP:
        - "Azure OpenAI Setup": setup/openai.md
        - "Azure AI Model Setup": setup/azure-ai.md
        - "GitHub Model Setup": setup/github.md
        - "ONNX Phi-3 Setup": setup/onnx.md
  - OPENAI:
    - "Azure OpenAI Setup": setup/openai.md
    - CHAT API:
      - "\u2460 Chat Basics": openai-chat/basics.md
      - "\u2461 w/ Function Calling": openai-chat/functions.md
      - "\u2462 w/ RAG + AI Search": openai-chat/ai-search.md
    - ASSISTANTS API:
      - "\u2460 Assistants Overview": openai-asst/overview.md
      - "\u2461 Assistants Basics": openai-asst/basics.md
      - "\u2462 w/ Code Interpreter": openai-asst/code-interpreter.md
      - "\u2463 w/ Function Calling": openai-asst/functions.md
      - "\u2464 w/ File Search": openai-asst/file-search.md
  - AZURE AI:
    - "Azure AI Model Setup": setup/azure-ai.md
    - "\u2460 &nbsp; AI Model Basics": azure-ai-chat/basics.md
  - GITHUB:
    - "GitHub Model Setup": setup/github.md
    - "\u2460 &nbsp; GitHub Model Basics": github-chat/basics.md
  - ONNX and PHI-3:
    - "ONNX Phi-3 Setup": setup/onnx.md
    - "\u2460 &nbsp; ONNX Basics": onnx-chat/basics.md
    - "\u2461 &nbsp; w/ Function Calling": onnx-chat/functions.md
  - SPEECH:
    - "Speech Setup": setup/speech.md
    - "\u2460 &nbsp; Synthesis": speech/synthesis.md
    - "\u2461 &nbsp; Recognition": speech/recognition.md
    - "\u2462 &nbsp; Translation": speech/translation.md
    - "\u2463 &nbsp; w/ Keyword": speech/keyword-recognition.md
  - MULTI_MODAL:
    - "\u2460 Multi-Modal AI": chapter-25-multi-modal-ai.md
    - "\u2461 w/ Speech Input": chapter-26-chat-completions-w-speech-input.md
    - "\u2462 w/ Speech Input and Output": chapter-27-chat-completions-w-speech-input-and-output.md
    - "\u2463 w/ Image Input": chapter-28-chat-completions-w-image-input.md
    - "\u2464 w/ Image Output": chapter-29-chat-completions-w-image-output.md
  - AGENTS:
    - SEMANTIC KERNEL:
      - "\u2460 Semantic Kernel Basics": chapter-30-semantic-kernel-basics.md
      - "\u2461 w/ Function Calling": chapter-31-semantic-kernel-w-function-calling.md
      - "\u2462 w/ Basic Agents": chapter-32-semantic-kernel-w-basic-agents.md
      - "\u2463 w/ Advanced Agents": chapter-33-semantic-kernel-w-advanced-agents.md
  - REFERENCE:
    - ai cli:
      - reference/cli/index.md
      - "ai init": reference/cli/init.md
      - "ai config": reference/cli/config.md
      - "ai chat":
        - reference/cli/chat/index.md
        - "assistant":
          - reference/cli/chat/assistant/index.md
          - "create": reference/cli/chat/assistant/create.md
          - "delete": reference/cli/chat/assistant/delete.md
          - "get": reference/cli/chat/assistant/get.md
          - "list": reference/cli/chat/assistant/list.md
          - "update": reference/cli/chat/assistant/update.md
          - "file":
            - reference/cli/chat/assistant/file/index.md
            - "delete": reference/cli/chat/assistant/file/delete.md
            - "list": reference/cli/chat/assistant/file/list.md
            - "upload": reference/cli/chat/assistant/file/upload.md
          - "vector-store":
            - reference/cli/chat/assistant/vector-store/index.md
            - "create": reference/cli/chat/assistant/vector-store/create.md
            - "delete": reference/cli/chat/assistant/vector-store/delete.md
            - "get": reference/cli/chat/assistant/vector-store/get.md
            - "list": reference/cli/chat/assistant/vector-store/list.md
            - "update": reference/cli/chat/assistant/vector-store/update.md
      - "ai dev":
        - reference/cli/dev/index.md
        - "new":
          - reference/cli/dev/new/index.md
          - "list": reference/cli/dev/new/list.md
        - "shell": reference/cli/dev/shell.md
      - "ai search":
        - "index":
          - reference/cli/search/index/index.md
          - "create": reference/cli/search/index/create.md
          - "update": reference/cli/search/index/update.md
      - "ai speech":
        - reference/cli/speech/index.md
        - "recognize": reference/cli/speech/recognize.md
        - "synthesize": reference/cli/speech/synthesize.md
        - "transcribe": reference/cli/speech/transcribe.md
        - "translate": reference/cli/speech/translate.md
        - "intent": reference/cli/speech/intent.md
        - "batch":
          - reference/cli/speech/batch/index.md
          - "transcription":
            - reference/cli/speech/batch/transcription/index.md
            - "create": reference/cli/speech/batch/transcription/create.md
            - "delete": reference/cli/speech/batch/transcription/delete.md
            - "download": reference/cli/speech/batch/transcription/download.md
            - "list": reference/cli/speech/batch/transcription/list.md
            - "status": reference/cli/speech/batch/transcription/status.md
            - "update": reference/cli/speech/batch/transcription/update.md
        - "csr":
          - reference/cli/speech/csr/index.md
          - "dataset":
            - reference/cli/speech/csr/dataset/index.md
            - "create": reference/cli/speech/csr/dataset/create.md
            - "delete": reference/cli/speech/csr/dataset/delete.md
            - "download": reference/cli/speech/csr/dataset/download.md
            - "list": reference/cli/speech/csr/dataset/list.md
            - "status": reference/cli/speech/csr/dataset/status.md
            - "update": reference/cli/speech/csr/dataset/update.md
            - "upload": reference/cli/speech/csr/dataset/upload.md
          - "endpoint":
            - reference/cli/speech/csr/endpoint/index.md
            - "create": reference/cli/speech/csr/endpoint/create.md
            - "delete": reference/cli/speech/csr/endpoint/delete.md
            - "download": reference/cli/speech/csr/endpoint/download.md
            - "list": reference/cli/speech/csr/endpoint/list.md
            - "status": reference/cli/speech/csr/endpoint/status.md
            - "update": reference/cli/speech/csr/endpoint/update.md
          - "evaluation":
            - reference/cli/speech/csr/evaluation/index.md
            - "create": reference/cli/speech/csr/evaluation/create.md
            - "delete": reference/cli/speech/csr/evaluation/delete.md
            - "list": reference/cli/speech/csr/evaluation/list.md
            - "status": reference/cli/speech/csr/evaluation/status.md
            - "update": reference/cli/speech/csr/evaluation/update.md
          - "model":
            - reference/cli/speech/csr/model/index.md
            - "copy": reference/cli/speech/csr/model/copy.md
            - "create": reference/cli/speech/csr/model/create.md
            - "delete": reference/cli/speech/csr/model/delete.md
            - "list": reference/cli/speech/csr/model/list.md
            - "status": reference/cli/speech/csr/model/status.md
            - "update": reference/cli/speech/csr/model/update.md
          - "project":
            - reference/cli/speech/csr/project/index.md
            - "create": reference/cli/speech/csr/project/create.md
            - "delete": reference/cli/speech/csr/project/delete.md
            - "list": reference/cli/speech/csr/project/list.md
            - "status": reference/cli/speech/csr/project/status.md
            - "update": reference/cli/speech/csr/project/update.md
        - "profile":
          - reference/cli/speech/profile/index.md
          - "create": reference/cli/speech/profile/create.md
          - "delete": reference/cli/speech/profile/delete.md
          - "enroll": reference/cli/speech/profile/enroll.md
          - "list": reference/cli/speech/profile/list.md
          - "status": reference/cli/speech/profile/status.md
        - "speaker":
          - reference/cli/speech/speaker/index.md
          - "identify": reference/cli/speech/speaker/identify.md
          - "verify": reference/cli/speech/speaker/verify.md
      - "ai test":
        - reference/cli/test/index.md
        - "list": reference/cli/test/list.md
        - "run": reference/cli/test/run.md
        - "yaml": reference/test-framework/yaml.md
