site_name: BOOK of AI
repo_url: https://github.com/robch/book-of-ai

theme:
  logo: assets/ai.png
  name: material
  icon:
    annotation: material/arrow-right-circle 
  features:
  - navigation.tabs     # once there are multiple books, uncomment this
  - navigation.sections
  # - navigation.footer
  - navigation.indexes
  # - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: en
  palette:
  - scheme: default
    toggle: 
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: black
    accent: indigo
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: black
    accent: indigo

extra_css:
  - assets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/spacetimeglitch
    - icon: fontawesome/brands/github
      link: https://github.com/robch
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/chambersrob/

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower      
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs", "docs/snippets", "snippets"]
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

copyright: |
  &copy; 2024 <a href="https://github.com/robch/" target="_blank" rel="noopener">Rob Chambers</a>

nav:
  - HOME: index.md
  - PRE-REQS:
      - INSTALL:
        - "CLI Installation": install-ai-cli.md
      - SETUP:
        - "Azure OpenAI Setup": setup/openai.md
        - "Azure AI Model Setup": setup/azure-ai.md
        - "GitHub Model Setup": setup/github.md
        - "ONNX Phi-3 Setup": setup/onnx.md
  - OPENAI:
    - "Azure OpenAI Setup": setup/openai.md
    - CHAT API:
      - "\u2460 Chat Basics": openai-chat/basics.md
      - "\u2461 w/ Function Calling": openai-chat/functions.md
      - "\u2462 w/ RAG + AI Search": openai-chat/ai-search.md
    - ASSISTANTS API:
      - "\u2460 Assistants Overview": openai-asst/overview.md
      - "\u2461 Assistants Basics": openai-asst/basics.md
      - "\u2462 w/ Code Interpreter": openai-asst/code-interpreter.md
      - "\u2463 w/ Function Calling": openai-asst/functions.md
      - "\u2464 w/ File Search": openai-asst/file-search.md
  - AZURE AI:
    - "Azure AI Model Setup": setup/azure-ai.md
    - "\u2460 &nbsp; AI Model Basics": azure-ai-chat/basics.md
  - GITHUB:
    - "GitHub Model Setup": setup/github.md
    - "\u2460 &nbsp; GitHub Model Basics": github-chat/basics.md
  - ONNX and PHI-3:
    - "ONNX Phi-3 Setup": setup/onnx.md
    - "\u2460 &nbsp; ONNX Basics": onnx-chat/basics.md
    - "\u2461 &nbsp; w/ Function Calling": onnx-chat/functions.md
  - SPEECH:
    - "Speech Setup": setup/speech.md
    - "\u2460 &nbsp; Synthesis": speech/synthesis.md
    - "\u2461 &nbsp; Recognition": speech/recognition.md
    - "\u2462 &nbsp; Translation": speech/translation.md
    - "\u2463 &nbsp; w/ Keyword": speech/keyword-recognition.md
  - MULTI_MODAL:
    - "\u2460 Multi-Modal AI": chapter-25-multi-modal-ai.md
    - "\u2461 w/ Speech Input": chapter-26-chat-completions-w-speech-input.md
    - "\u2462 w/ Speech Input and Output": chapter-27-chat-completions-w-speech-input-and-output.md
    - "\u2463 w/ Image Input": chapter-28-chat-completions-w-image-input.md
    - "\u2464 w/ Image Output": chapter-29-chat-completions-w-image-output.md
  - AGENTS:
    - SEMANTIC KERNEL:
      - "\u2460 Semantic Kernel Basics": chapter-30-semantic-kernel-basics.md
      - "\u2461 w/ Function Calling": chapter-31-semantic-kernel-w-function-calling.md
      - "\u2462 w/ Basic Agents": chapter-32-semantic-kernel-w-basic-agents.md
      - "\u2463 w/ Advanced Agents": chapter-33-semantic-kernel-w-advanced-agents.md
  - REFERENCE:
    - ai:
      - "ai init": reference/cli/ai-init.md
      - "ai config": reference/cli/ai-config.md
      - "ai chat": reference/cli/ai-chat.md
      - "ai chat assistant":
        - "create": reference/cli/ai-chat-assistant-create.md
        - "delete": reference/cli/ai-chat-assistant-delete.md
        - "get": reference/cli/ai-chat-assistant-get.md
        - "list": reference/cli/ai-chat-assistant-list.md
        - "update": reference/cli/ai-chat-assistant-update.md
        - "file":
          - "delete": reference/cli/ai-chat-assistant-file-delete.md
          - "list": reference/cli/ai-chat-assistant-file-list.md
          - "upload": reference/cli/ai-chat-assistant-file-upload.md
        - "vector-store":
          - "create": reference/cli/ai-chat-assistant-vector-store-create.md
          - "delete": reference/cli/ai-chat-assistant-vector-store-delete.md
          - "get": reference/cli/ai-chat-assistant-vector-store-get.md
          - "list": reference/cli/ai-chat-assistant-vector-store-list.md
          - "update": reference/cli/ai-chat-assistant-vector-store-update.md
      - "ai dev":
        - "new": reference/cli/ai-dev-new.md
        - "new list": reference/cli/ai-dev-new-list.md
        - "shell": reference/cli/ai-dev-shell.md
      - "ai search":
        - "index create": reference/cli/ai-search-index-create.md
        - "index update": reference/cli/ai-search-index-update.md
      - "ai speech":
        - "recognize": reference/cli/ai-speech-recognize.md
        - "synthesize": reference/cli/ai-speech-synthesize.md
        - "translate": reference/cli/ai-speech-translate.md
        - "csr":
          - "dataset":
            - "create": reference/cli/ai-speech-csr-dataset-create.md
            - "delete": reference/cli/ai-speech-csr-dataset-delete.md
            - "download": reference/cli/ai-speech-csr-dataset-download.md
            - "list": reference/cli/ai-speech-csr-dataset-list.md
            - "status": reference/cli/ai-speech-csr-dataset-status.md
            - "update": reference/cli/ai-speech-csr-dataset-update.md
            - "upload": reference/cli/ai-speech-csr-dataset-upload.md
          - "endpoint":
            - "create": reference/cli/ai-speech-csr-endpoint-create.md
            - "delete": reference/cli/ai-speech-csr-endpoint-delete.md
            - "download": reference/cli/ai-speech-csr-endpoint-download.md
            - "list": reference/cli/ai-speech-csr-endpoint-list.md
            - "status": reference/cli/ai-speech-csr-endpoint-status.md
            - "update": reference/cli/ai-speech-csr-endpoint-update.md
          - "evaluation":
            - "create": reference/cli/ai-speech-csr-evaluation-create.md
            - "delete": reference/cli/ai-speech-csr-evaluation-delete.md
            - "list": reference/cli/ai-speech-csr-evaluation-list.md
            - "status": reference/cli/ai-speech-csr-evaluation-status.md
            - "update": reference/cli/ai-speech-csr-evaluation-update.md
          - "model":
            - "copy": reference/cli/ai-speech-csr-model-copy.md
            - "create": reference/cli/ai-speech-csr-model-create.md
            - "delete": reference/cli/ai-speech-csr-model-delete.md
            - "list": reference/cli/ai-speech-csr-model-list.md
            - "status": reference/cli/ai-speech-csr-model-status.md
            - "update": reference/cli/ai-speech-csr-model-update.md
          - "project":
            - "create": reference/cli/ai-speech-csr-project-create.md
            - "delete": reference/cli/ai-speech-csr-project-delete.md
            - "list": reference/cli/ai-speech-csr-project-list.md
            - "status": reference/cli/ai-speech-csr-project-status.md
            - "update": reference/cli/ai-speech-csr-project-update.md
        - "batch transcription":
          - "create": reference/cli/ai-speech-batch-transcription-create.md
          - "delete": reference/cli/ai-speech-batch-transcription-delete.md
          - "download": reference/cli/ai-speech-batch-transcription-download.md
          - "list": reference/cli/ai-speech-batch-transcription-list.md
          - "status": reference/cli/ai-speech-batch-transcription-status.md
          - "update": reference/cli/ai-speech-batch-transcription-update.md
        - "transcribe": reference/cli/ai-speech-transcribe.md
        - "intent": reference/cli/ai-speech-intent.md
        - "profile":
          - "create": reference/cli/ai-speech-profile-create.md
          - "delete": reference/cli/ai-speech-profile-delete.md
          - "enroll": reference/cli/ai-speech-profile-enroll.md
          - "list": reference/cli/ai-speech-profile-list.md
          - "status": reference/cli/ai-speech-profile-status.md
        - "speaker":
          - "identify": reference/cli/ai-speech-speaker-identify.md
          - "verify": reference/cli/ai-speech-speaker-verify.md
      - "ai test":
        - "list": reference/cli/ai-test-list.md
        - "run": reference/cli/ai-test-run.md
